metal:
 children:
  masters:
   hosts:
    metal1: { ansible_host: 192.168.1.108, mac: '00:23:24:b9:8b:3d', disk: sda, network_interface: eno1 }
  workers:
   hosts:
    metal2: { ansible_host: 192.168.1.107, mac: '00:23:24:bf:20:02', disk: sda, network_interface: eno1 }
